baseURL: "http://example.org/"
languageCode: "en-us"
title: "My portfolio Profile Site"
theme: "My-portfolio"

params:
  title: "Krishna Bindu"
  subtitle: "Web Developer / UI/UX Designer, "
  description: "A simple portfolio5 site built with Hugo and hugo-profile theme"
  avatar: "images/avatar.jpg"
  favicon: "images/favicon.png"

menu:
  main:
    - identifier: about
      name: About
      url: /about
      weight: 1
    - identifier: projects
      name: Projects
      url: /projects
      weight: 2
    - identifier: contact
      name: Contact
      url: /contact
      weight: 3
